Butname: HYIP Cron Bot
on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Cron URL
        run: |
          curl -L -k -v -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
          -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8" \
          -H "Accept-Language: en-US,en;q=0.5" \
          https://ah25.rf.gd/cron
